<?php

$routes = [
    '/' => ['controller' => 'HomeController', 'action' => 'index'],
    '/home' => ['controller' => 'HomeController', 'action' => 'index'],
    '/sitemap.xml' => ['controller' => 'SEOController', 'action' => 'sitemap'],
    '/robots.txt' => ['controller' => 'SEOController', 'action' => 'robots'],
    '/manifest.json' => ['controller' => 'SEOController', 'action' => 'manifest'],
    '/dashboard' => ['controller' => 'DashboardController', 'action' => 'index'],
    '/login' => ['controller' => 'AuthController', 'action' => 'loginForm'],
    '/login/post' => ['controller' => 'AuthController', 'action' => 'login'],
    '/logout' => ['controller' => 'AuthController', 'action' => 'logout'],
    '/register' => ['controller' => 'AuthController', 'action' => 'registerForm'],
    '/register/post' => ['controller' => 'AuthController', 'action' => 'register'],
    '/verify-email' => ['controller' => 'AuthController', 'action' => 'verifyEmailForm'],
    '/verify-email/resend' => ['controller' => 'AuthController', 'action' => 'resendVerification'],
    '/users' => ['controller' => 'UserController', 'action' => 'index'],
    '/users/create' => ['controller' => 'UserController', 'action' => 'create'],
    '/users/store' => ['controller' => 'UserController', 'action' => 'store'],
    '/users/edit/{id}' => ['controller' => 'UserController', 'action' => 'edit'],
    '/users/update/{id}' => ['controller' => 'UserController', 'action' => 'update'],
    '/users/delete/{id}' => ['controller' => 'UserController', 'action' => 'delete'],
    '/logs' => ['controller' => 'LogController', 'action' => 'index'],
    '/logs/show/{id}' => ['controller' => 'LogController', 'action' => 'show'],
    '/logs/clear' => ['controller' => 'LogController', 'action' => 'clear'],
    '/settings' => ['controller' => 'SettingController', 'action' => 'index'],
    '/settings/edit/{id}' => ['controller' => 'SettingController', 'action' => 'edit'],
    '/settings/update/{id}' => ['controller' => 'SettingController', 'action' => 'update'],
    '/settings/appearance' => ['controller' => 'SettingsController', 'action' => 'appearance'],
    '/settings/update-theme' => ['controller' => 'SettingsController', 'action' => 'updateTheme'],
    '/members' => ['controller' => 'MemberController', 'action' => 'index'],
    '/members/create' => ['controller' => 'MemberController', 'action' => 'create'],
    '/members/store' => ['controller' => 'MemberController', 'action' => 'store'],
    '/members/show/{id}' => ['controller' => 'MemberController', 'action' => 'show'],
    '/members/edit/{id}' => ['controller' => 'MemberController', 'action' => 'edit'],
    '/members/update/{id}' => ['controller' => 'MemberController', 'action' => 'update'],
    '/events' => ['controller' => 'EventController', 'action' => 'index'],
    '/events/create' => ['controller' => 'EventController', 'action' => 'create'],
    '/events/store' => ['controller' => 'EventController', 'action' => 'store'],
    '/events/show/{id}' => ['controller' => 'EventController', 'action' => 'show'],
    '/events/edit/{id}' => ['controller' => 'EventController', 'action' => 'edit'],
    '/events/update/{id}' => ['controller' => 'EventController', 'action' => 'update'],
    '/events/delete/{id}' => ['controller' => 'EventController', 'action' => 'delete'],
    '/events/add-photo/{id}' => ['controller' => 'EventController', 'action' => 'addPhoto'],
    '/events/delete-photo/{id}' => ['controller' => 'EventController', 'action' => 'deletePhoto'],
    '/payments' => ['controller' => 'PaymentController', 'action' => 'index'],
    '/payments/create' => ['controller' => 'PaymentController', 'action' => 'create'],
    '/payments/store' => ['controller' => 'PaymentController', 'action' => 'store'],
    '/payments/show/{id}' => ['controller' => 'PaymentController', 'action' => 'show'],
    '/payments/edit/{id}' => ['controller' => 'PaymentController', 'action' => 'edit'],
    '/payments/update/{id}' => ['controller' => 'PaymentController', 'action' => 'update'],
    '/payments/delete/{id}' => ['controller' => 'PaymentController', 'action' => 'delete'],
    '/notifications' => ['controller' => 'NotificationController', 'action' => 'index'],
    '/notifications/create' => ['controller' => 'NotificationController', 'action' => 'create'],
    '/notifications/store' => ['controller' => 'NotificationController', 'action' => 'store'],
    '/notifications/show/{id}' => ['controller' => 'NotificationController', 'action' => 'show'],
    '/notifications/mark-as-unread/{id}' => ['controller' => 'NotificationController', 'action' => 'markAsUnread'],
    '/notifications/delete/{id}' => ['controller' => 'NotificationController', 'action' => 'delete'],
    '/notifications/send-pending' => ['controller' => 'NotificationController', 'action' => 'sendPending'],
    '/reports' => ['controller' => 'ReportController', 'action' => 'index'],
    '/reports/dashboard' => ['controller' => 'ReportController', 'action' => 'dashboard'],
    '/reports/members' => ['controller' => 'ReportController', 'action' => 'members'],
    '/reports/payments' => ['controller' => 'ReportController', 'action' => 'payments'],
    '/reports/events' => ['controller' => 'ReportController', 'action' => 'events'],
    '/reports/export-members/{format}' => ['controller' => 'ReportController', 'action' => 'exportMembers'],
    '/reports/export-payments/{format}' => ['controller' => 'ReportController', 'action' => 'exportPayments'],
    '/reports/export-events/{format}' => ['controller' => 'ReportController', 'action' => 'exportEvents'],
    '/backups' => ['controller' => 'BackupController', 'action' => 'index'],
    '/backups/create' => ['controller' => 'BackupController', 'action' => 'create'],
    '/backups/download/{filename}' => ['controller' => 'BackupController', 'action' => 'download'],
    '/backups/delete/{filename}' => ['controller' => 'BackupController', 'action' => 'delete'],
    '/backups/restore/{filename}' => ['controller' => 'BackupController', 'action' => 'restore'],
    '/motorcycles' => ['controller' => 'MotorcycleController', 'action' => 'index'],
    '/motorcycles/create' => ['controller' => 'MotorcycleController', 'action' => 'create'],
    '/motorcycles/store' => ['controller' => 'MotorcycleController', 'action' => 'store'],
    '/motorcycles/show/{id}' => ['controller' => 'MotorcycleController', 'action' => 'show'],
    '/motorcycles/edit/{id}' => ['controller' => 'MotorcycleController', 'action' => 'edit'],
    '/motorcycles/update/{id}' => ['controller' => 'MotorcycleController', 'action' => 'update'],
    '/motorcycles/delete/{id}' => ['controller' => 'MotorcycleController', 'action' => 'delete'],
    '/motorcycles/update-photo-caption/{id}' => ['controller' => 'MotorcycleController', 'action' => 'updatePhotoCaption'],
    '/motorcycles/add-photo/{id}' => ['controller' => 'MotorcycleController', 'action' => 'addPhoto'],
    '/motorcycles/delete-photo/{id}' => ['controller' => 'MotorcycleController', 'action' => 'deletePhoto'],
    '/motorcycle-brands' => ['controller' => 'MotorcycleBrandController', 'action' => 'index'],
    '/motorcycle-brands/create' => ['controller' => 'MotorcycleBrandController', 'action' => 'create'],
    '/motorcycle-brands/store' => ['controller' => 'MotorcycleBrandController', 'action' => 'store'],
    '/motorcycle-brands/edit/{id}' => ['controller' => 'MotorcycleBrandController', 'action' => 'edit'],
    '/motorcycle-brands/update/{id}' => ['controller' => 'MotorcycleBrandController', 'action' => 'update'],
    '/motorcycle-brands/delete/{id}' => ['controller' => 'MotorcycleBrandController', 'action' => 'delete'],
    '/clubs' => ['controller' => 'ClubController', 'action' => 'index'],
    '/clubs/create' => ['controller' => 'ClubController', 'action' => 'create'],
    '/clubs/store' => ['controller' => 'ClubController', 'action' => 'store'],
    '/clubs/show/{id}' => ['controller' => 'ClubController', 'action' => 'show'],
    '/clubs/join/{id}' => ['controller' => 'ClubController', 'action' => 'join'],
    '/clubs/claim-form/{id}' => ['controller' => 'ClubController', 'action' => 'claimForm'],
    '/clubs/claim/{id}' => ['controller' => 'ClubController', 'action' => 'claim'],
    '/clubs/edit/{id}' => ['controller' => 'ClubController', 'action' => 'edit'],
    '/clubs/update/{id}' => ['controller' => 'ClubController', 'action' => 'update'],
    '/clubs/delete/{id}' => ['controller' => 'ClubController', 'action' => 'delete'],
    '/clubs/upload-logo/{id}' => ['controller' => 'ClubController', 'action' => 'uploadLogo'],
    '/clubs/upload-photo/{id}' => ['controller' => 'ClubController', 'action' => 'uploadPhoto'],
    '/clubs/delete-photo/{id}' => ['controller' => 'ClubController', 'action' => 'deletePhoto'],
    '/clubs/cities' => ['controller' => 'ClubController', 'action' => 'searchCities'],
    '/clubs/map-data' => ['controller' => 'ClubController', 'action' => 'mapData'],
    '/clubs/map-public' => ['controller' => 'ClubController', 'action' => 'mapPublic'],
    '/clubs/map-click-log' => ['controller' => 'ClubController', 'action' => 'logMapClick'],
    '/clubs/{id}/members/add' => ['controller' => 'ClubController', 'action' => 'addMember'],
    '/clubs/{id}/members/approve/{userId}' => ['controller' => 'ClubController', 'action' => 'approveMember'],
    '/clubs/{id}/members/remove/{userId}' => ['controller' => 'ClubController', 'action' => 'removeMember'],
    '/clubs/{id}/members/promote/{userId}' => ['controller' => 'ClubController', 'action' => 'promoteMember'],
    '/stories' => ['controller' => 'StoryController', 'action' => 'index'],
    '/stories/create' => ['controller' => 'StoryController', 'action' => 'create'],
    '/stories/store' => ['controller' => 'StoryController', 'action' => 'store'],
    '/stories/upload-image' => ['controller' => 'StoryController', 'action' => 'uploadImage'],
    '/stories/show/{id}' => ['controller' => 'StoryController', 'action' => 'show'],
    '/stories/edit/{id}' => ['controller' => 'StoryController', 'action' => 'edit'],
    '/stories/update/{id}' => ['controller' => 'StoryController', 'action' => 'update'],
    '/stories/delete/{id}' => ['controller' => 'StoryController', 'action' => 'delete'],
    '/stories/comment-delete/{id}' => ['controller' => 'StoryController', 'action' => 'deleteComment'],
    '/forum' => ['controller' => 'ForumController', 'action' => 'index'],
    '/forum/create' => ['controller' => 'ForumController', 'action' => 'create'],
    '/forum/store' => ['controller' => 'ForumController', 'action' => 'store'],
    '/forum/show/{id}' => ['controller' => 'ForumController', 'action' => 'show'],
    '/forum/reply/{id}' => ['controller' => 'ForumController', 'action' => 'reply'],
    '/forum/delete/{id}' => ['controller' => 'ForumController', 'action' => 'delete'],
    '/forum/reply-delete/{id}' => ['controller' => 'ForumController', 'action' => 'deleteReply'],
    '/travels' => ['controller' => 'TravelController', 'action' => 'index'],
    '/travels/create' => ['controller' => 'TravelController', 'action' => 'create'],
    '/travels/store' => ['controller' => 'TravelController', 'action' => 'store'],
    '/travels/show/{id}' => ['controller' => 'TravelController', 'action' => 'show'],
    '/travels/delete/{id}' => ['controller' => 'TravelController', 'action' => 'delete'],
    '/reputation' => ['controller' => 'ReputationController', 'action' => 'index'],
    '/reputation/show/{id}' => ['controller' => 'ReputationController', 'action' => 'show'],
    '/map' => ['controller' => 'MapController', 'action' => 'index'],
    '/verifications' => ['controller' => 'VerificationController', 'action' => 'index'],
    '/verifications/create' => ['controller' => 'VerificationController', 'action' => 'create'],
    '/verifications/store' => ['controller' => 'VerificationController', 'action' => 'store'],
    '/verifications/show/{id}' => ['controller' => 'VerificationController', 'action' => 'show'],
    '/verifications/approve/{id}' => ['controller' => 'VerificationController', 'action' => 'approve'],
    '/verifications/reject/{id}' => ['controller' => 'VerificationController', 'action' => 'reject'],
    '/marketplace' => ['controller' => 'MarketplaceController', 'action' => 'index'],
    '/marketplace/create' => ['controller' => 'MarketplaceController', 'action' => 'create'],
    '/marketplace/store' => ['controller' => 'MarketplaceController', 'action' => 'store'],
    '/marketplace/show/{id}' => ['controller' => 'MarketplaceController', 'action' => 'show'],
    '/marketplace/my-listings' => ['controller' => 'MarketplaceController', 'action' => 'myListings'],
    '/marketplace/delete/{id}' => ['controller' => 'MarketplaceController', 'action' => 'delete'],
    '/guardian' => ['controller' => 'GuardianController', 'action' => 'index'],
    '/guardian/create-session' => ['controller' => 'GuardianController', 'action' => 'createSession'],
    '/guardian/store-session' => ['controller' => 'GuardianController', 'action' => 'storeSession'],
    '/guardian/session/{id}' => ['controller' => 'GuardianController', 'action' => 'showSession'],
    '/guardian/update-location/{id}' => ['controller' => 'GuardianController', 'action' => 'updateLocation'],
    '/guardian/end-session/{id}' => ['controller' => 'GuardianController', 'action' => 'endSession'],
    '/guardian/create-contact' => ['controller' => 'GuardianController', 'action' => 'createContact'],
    '/guardian/store-contact' => ['controller' => 'GuardianController', 'action' => 'storeContact'],
    '/guardian/delete-contact/{id}' => ['controller' => 'GuardianController', 'action' => 'deleteContact'],
    '/guardian/send-sos' => ['controller' => 'GuardianController', 'action' => 'sendSOS'],
    '/guardian/share-session/{id}' => ['controller' => 'GuardianController', 'action' => 'shareSession'],
    '/guardian/groups' => ['controller' => 'GuardianGroupController', 'action' => 'index'],
    '/guardian/groups/create' => ['controller' => 'GuardianGroupController', 'action' => 'create'],
    '/guardian/groups/store' => ['controller' => 'GuardianGroupController', 'action' => 'store'],
    '/guardian/groups/show/{id}' => ['controller' => 'GuardianGroupController', 'action' => 'show'],
    '/guardian/groups/join' => ['controller' => 'GuardianGroupController', 'action' => 'join'],
    '/guardian/groups/leave/{id}' => ['controller' => 'GuardianGroupController', 'action' => 'leave'],
    '/guardian/groups/delete/{id}' => ['controller' => 'GuardianGroupController', 'action' => 'delete'],
    '/emergency' => ['controller' => 'EmergencyController', 'action' => 'index'],
    '/emergency/create-contact' => ['controller' => 'EmergencyController', 'action' => 'createContact'],
    '/emergency/store-contact' => ['controller' => 'EmergencyController', 'action' => 'storeContact'],
    '/emergency/delete-contact/{id}' => ['controller' => 'EmergencyController', 'action' => 'deleteContact'],
    '/emergency/create-service' => ['controller' => 'EmergencyController', 'action' => 'createService'],
    '/emergency/store-service' => ['controller' => 'EmergencyController', 'action' => 'storeService'],
    '/emergency/delete-service/{id}' => ['controller' => 'EmergencyController', 'action' => 'deleteService'],
    '/emergency/trigger-panic' => ['controller' => 'EmergencyController', 'action' => 'triggerPanic'],
    '/emergency/resolve-alert/{id}' => ['controller' => 'EmergencyController', 'action' => 'resolveAlert'],
    '/memorial' => ['controller' => 'MemorialController', 'action' => 'index'],
    '/memorial/create' => ['controller' => 'MemorialController', 'action' => 'create'],
    '/memorial/store' => ['controller' => 'MemorialController', 'action' => 'store'],
    '/memorial/show/{id}' => ['controller' => 'MemorialController', 'action' => 'show'],
    '/memorial/add-message/{id}' => ['controller' => 'MemorialController', 'action' => 'addMessage'],
    '/memorial/delete/{id}' => ['controller' => 'MemorialController', 'action' => 'delete'],
    '/memorial/like/{id}' => ['controller' => 'MemorialController', 'action' => 'like'],
    '/memorial/dislike/{id}' => ['controller' => 'MemorialController', 'action' => 'dislike'],
    '/album' => ['controller' => 'AlbumController', 'action' => 'index'],
    '/album/create' => ['controller' => 'AlbumController', 'action' => 'create'],
    '/album/store' => ['controller' => 'AlbumController', 'action' => 'store'],
    '/album/show/{id}' => ['controller' => 'AlbumController', 'action' => 'show'],
    '/album/upload-photo/{id}' => ['controller' => 'AlbumController', 'action' => 'uploadPhoto'],
    '/album/upload-cover/{id}' => ['controller' => 'AlbumController', 'action' => 'uploadCover'],
    '/album/delete-photo/{id}' => ['controller' => 'AlbumController', 'action' => 'deletePhoto'],
    '/album/delete/{id}' => ['controller' => 'AlbumController', 'action' => 'delete'],
    '/album/comment/{id}' => ['controller' => 'AlbumController', 'action' => 'addComment'],
    '/album/comment-delete/{id}' => ['controller' => 'AlbumController', 'action' => 'deleteComment'],
    '/album/like/{id}' => ['controller' => 'AlbumController', 'action' => 'toggleLike'],
    '/partners' => ['controller' => 'PartnerController', 'action' => 'index'],
    '/partners/create' => ['controller' => 'PartnerController', 'action' => 'create'],
    '/partners/store' => ['controller' => 'PartnerController', 'action' => 'store'],
    '/partners/show/{id}' => ['controller' => 'PartnerController', 'action' => 'show'],
    '/partners/delete/{id}' => ['controller' => 'PartnerController', 'action' => 'delete'],
    '/partners/claim/{token}' => ['controller' => 'PartnerController', 'action' => 'claim'],
    '/partners/claim-store' => ['controller' => 'PartnerController', 'action' => 'claimStore'],
    '/partners/search-cep' => ['controller' => 'PartnerController', 'action' => 'searchCep'],
    '/premium-clubs' => ['controller' => 'PremiumClubController', 'action' => 'index'],
    '/premium-clubs/create' => ['controller' => 'PremiumClubController', 'action' => 'create'],
    '/premium-clubs/store' => ['controller' => 'PremiumClubController', 'action' => 'store'],
    '/premium-clubs/show/{id}' => ['controller' => 'PremiumClubController', 'action' => 'show'],
    '/premium-clubs/cancel/{id}' => ['controller' => 'PremiumClubController', 'action' => 'cancel'],
    // API Routes
    '/api/users/login' => ['controller' => 'Api\\UserController', 'action' => 'login'],
    '/api/users' => ['controller' => 'Api\\UserController', 'action' => 'index'],
    '/api/users/{id}' => ['controller' => 'Api\\UserController', 'action' => 'show'],
    '/api/users/create' => ['controller' => 'Api\\UserController', 'action' => 'store'],
    '/api/users/update/{id}' => ['controller' => 'Api\\UserController', 'action' => 'update'],
    '/api/users/delete/{id}' => ['controller' => 'Api\\UserController', 'action' => 'destroy'],
    '/api/friends' => ['controller' => 'Api\\FriendController', 'action' => 'index'],
    '/api/friends/sos' => ['controller' => 'Api\\FriendController', 'action' => 'sendSos'],
    '/api/motorcycles' => ['controller' => 'Api\\MotorcycleController', 'action' => 'index'],
    '/api/motorcycles/{id}' => ['controller' => 'Api\\MotorcycleController', 'action' => 'show'],
    '/api/motorcycles/create' => ['controller' => 'Api\\MotorcycleController', 'action' => 'store'],
    '/api/motorcycles/update/{id}' => ['controller' => 'Api\\MotorcycleController', 'action' => 'update'],
    '/api/motorcycles/delete/{id}' => ['controller' => 'Api\\MotorcycleController', 'action' => 'destroy'],
    '/api/events' => ['controller' => 'Api\\EventController', 'action' => 'index'],
    '/api/events/{id}' => ['controller' => 'Api\\EventController', 'action' => 'show'],
    '/api/events/create' => ['controller' => 'Api\\EventController', 'action' => 'store'],
    '/api/events/update/{id}' => ['controller' => 'Api\\EventController', 'action' => 'update'],
    '/api/events/delete/{id}' => ['controller' => 'Api\\EventController', 'action' => 'destroy'],
    '/api/events/{id}/participate' => ['controller' => 'Api\\EventController', 'action' => 'participate'],
    '/api/events/{id}/participants' => ['controller' => 'Api\\EventController', 'action' => 'participants'],
    '/api/events/{id}/checkin' => ['controller' => 'Api\\EventController', 'action' => 'checkIn'],
    '/chatbot' => ['controller' => 'ChatbotController', 'action' => 'index'],
    '/chatbot/send' => ['controller' => 'ChatbotController', 'action' => 'sendMessage'],
    '/chatbot/history' => ['controller' => 'ChatbotController', 'action' => 'getHistory'],
    '/chatbot/clear-history' => ['controller' => 'ChatbotController', 'action' => 'clearHistory'],
    '/chatbot/recommendations' => ['controller' => 'ChatbotController', 'action' => 'getRecommendations'],
    
    // Profile
    '/profile' => ['controller' => 'ProfileController', 'action' => 'index'],
    '/profile/update' => ['controller' => 'ProfileController', 'action' => 'update'],
    '/profile/upload-avatar' => ['controller' => 'ProfileController', 'action' => 'uploadAvatar'],
    '/profile/upload-motorcycle' => ['controller' => 'ProfileController', 'action' => 'uploadMotorcyclePhoto'],
    '/profile/upload-photo' => ['controller' => 'ProfileController', 'action' => 'uploadPhoto'],
    '/profile/delete-photo' => ['controller' => 'ProfileController', 'action' => 'deletePhoto'],
    '/profile/delete-avatar' => ['controller' => 'ProfileController', 'action' => 'deleteAvatar'],
    '/profile/delete-motorcycle' => ['controller' => 'ProfileController', 'action' => 'deleteMotorcyclePhoto'],
    '/profile/send-verification' => ['controller' => 'ProfileController', 'action' => 'sendVerification'],
    '/referral/generate' => ['controller' => 'ReferralController', 'action' => 'generate'],
    '/referral/generate/post' => ['controller' => 'ReferralController', 'action' => 'generate'],
    '/referral/stats' => ['controller' => 'ReferralController', 'action' => 'stats'],
    '/r/{slug}' => ['controller' => 'ReferralController', 'action' => 'redirect'],
    
    // Friends
    '/friends' => ['controller' => 'FriendController', 'action' => 'index'],
    '/friends/send' => ['controller' => 'FriendController', 'action' => 'sendRequest'],
    '/friends/accept' => ['controller' => 'FriendController', 'action' => 'acceptRequest'],
    '/friends/decline' => ['controller' => 'FriendController', 'action' => 'declineRequest'],
    '/friends/remove' => ['controller' => 'FriendController', 'action' => 'removeFriend'],
    '/friends/search' => ['controller' => 'FriendController', 'action' => 'search'],
    '/friends/profile/{id}' => ['controller' => 'FriendController', 'action' => 'showProfile'],

    // Routes (Rotas Motociclísticas)
    '/routes' => ['controller' => 'RouteController', 'action' => 'index'],
    '/routes/create' => ['controller' => 'RouteController', 'action' => 'create'],
    '/routes/store' => ['controller' => 'RouteController', 'action' => 'store'],
    '/routes/show/{id}' => ['controller' => 'RouteController', 'action' => 'show'],
    '/routes/edit/{id}' => ['controller' => 'RouteController', 'action' => 'edit'],
    '/routes/update/{id}' => ['controller' => 'RouteController', 'action' => 'update'],
    '/routes/delete/{id}' => ['controller' => 'RouteController', 'action' => 'delete'],
    '/routes/add-photo/{id}' => ['controller' => 'RouteController', 'action' => 'addPhoto'],
    '/routes/delete-photo/{id}' => ['controller' => 'RouteController', 'action' => 'deletePhoto'],
    '/routes/add-review/{id}' => ['controller' => 'RouteController', 'action' => 'addReview'],
    '/routes/review-delete/{id}' => ['controller' => 'RouteController', 'action' => 'deleteReview'],
    '/routes/map' => ['controller' => 'RouteController', 'action' => 'map'],

    // Garage (Garagem Digital)
    '/garage' => ['controller' => 'GarageController', 'action' => 'index'],
    '/garage/maintenance/{id}' => ['controller' => 'GarageController', 'action' => 'maintenance'],
    '/garage/add-maintenance/{id}' => ['controller' => 'GarageController', 'action' => 'addMaintenance'],
    '/garage/delete-maintenance/{id}' => ['controller' => 'GarageController', 'action' => 'deleteMaintenance'],
    '/garage/fuel/{id}' => ['controller' => 'GarageController', 'action' => 'fuel'],
    '/garage/add-fuel/{id}' => ['controller' => 'GarageController', 'action' => 'addFuel'],
    '/garage/delete-fuel/{id}' => ['controller' => 'GarageController', 'action' => 'deleteFuel'],
    '/garage/expenses/{id}' => ['controller' => 'GarageController', 'action' => 'expenses'],
    '/garage/add-expense/{id}' => ['controller' => 'GarageController', 'action' => 'addExpense'],
    '/garage/delete-expense/{id}' => ['controller' => 'GarageController', 'action' => 'deleteExpense'],
    '/garage/modifications/{id}' => ['controller' => 'GarageController', 'action' => 'modifications'],
    '/garage/add-modification/{id}' => ['controller' => 'GarageController', 'action' => 'addModification'],
    '/garage/delete-modification/{id}' => ['controller' => 'GarageController', 'action' => 'deleteModification'],
    '/garage/equipment' => ['controller' => 'GarageController', 'action' => 'equipment'],
    '/garage/add-equipment' => ['controller' => 'GarageController', 'action' => 'addEquipment'],
    '/garage/delete-equipment/{id}' => ['controller' => 'GarageController', 'action' => 'deleteEquipment'],

    // Messages (Mensagens Privadas)
    '/messages' => ['controller' => 'MessageController', 'action' => 'index'],
    '/messages/show/{id}' => ['controller' => 'MessageController', 'action' => 'show'],
    '/messages/start/{id}' => ['controller' => 'MessageController', 'action' => 'start'],
    '/messages/send/{id}' => ['controller' => 'MessageController', 'action' => 'send'],
    '/messages/send-location/{id}' => ['controller' => 'MessageController', 'action' => 'sendLocation'],
    '/messages/create-group' => ['controller' => 'MessageController', 'action' => 'createGroup'],
    '/messages/store-group' => ['controller' => 'MessageController', 'action' => 'storeGroup'],
    '/messages/delete/{id}' => ['controller' => 'MessageController', 'action' => 'deleteMessage'],
    '/messages/mark-read/{id}' => ['controller' => 'MessageController', 'action' => 'markRead'],
    '/messages/fetch/{id}' => ['controller' => 'MessageController', 'action' => 'fetch'],

    // Follow (Seguidores)
    '/follow/{id}' => ['controller' => 'FollowController', 'action' => 'follow'],
    '/unfollow/{id}' => ['controller' => 'FollowController', 'action' => 'unfollow'],
    '/follow/toggle/{id}' => ['controller' => 'FollowController', 'action' => 'toggle'],
    '/followers' => ['controller' => 'FollowController', 'action' => 'followers'],
    '/followers/{id}' => ['controller' => 'FollowController', 'action' => 'followers'],
    '/following' => ['controller' => 'FollowController', 'action' => 'following'],
    '/following/{id}' => ['controller' => 'FollowController', 'action' => 'following'],
    '/follow/suggestions' => ['controller' => 'FollowController', 'action' => 'suggestions'],

    // Password Reset (Recuperação de Senha)
    '/forgot-password' => ['controller' => 'PasswordResetController', 'action' => 'forgotForm'],
    '/forgot-password/send' => ['controller' => 'PasswordResetController', 'action' => 'sendResetLink'],
    '/reset-password' => ['controller' => 'PasswordResetController', 'action' => 'resetForm'],
    '/reset-password/update' => ['controller' => 'PasswordResetController', 'action' => 'updatePassword'],

    // Email — Caixa de entrada admin + formulário de contato
    '/admin/mail' => ['controller' => 'MailController', 'action' => 'inbox'],
    '/admin/mail/read' => ['controller' => 'MailController', 'action' => 'read'],
    '/admin/mail/delete' => ['controller' => 'MailController', 'action' => 'delete'],
    '/admin/mail/unread' => ['controller' => 'MailController', 'action' => 'unreadCount'],
    '/contact' => ['controller' => 'MailController', 'action' => 'contactForm'],
    '/contact/send' => ['controller' => 'MailController', 'action' => 'contact'],

    // LGPD
    '/lgpd/terms' => ['controller' => 'LgpdController', 'action' => 'terms'],
    '/lgpd/privacy' => ['controller' => 'LgpdController', 'action' => 'privacy'],
    '/lgpd/community' => ['controller' => 'LgpdController', 'action' => 'community'],
    '/lgpd/marketplace' => ['controller' => 'LgpdController', 'action' => 'marketplace'],
    '/lgpd/commercial' => ['controller' => 'LgpdController', 'action' => 'commercial'],
    '/lgpd/events' => ['controller' => 'LgpdController', 'action' => 'events'],
    '/lgpd/safety' => ['controller' => 'LgpdController', 'action' => 'safety'],
    '/lgpd/cookies' => ['controller' => 'LgpdController', 'action' => 'cookies'],
    '/lgpd/intellectual-property' => ['controller' => 'LgpdController', 'action' => 'intellectualProperty'],
    '/lgpd/support' => ['controller' => 'LgpdController', 'action' => 'support'],
    '/lgpd/information-security' => ['controller' => 'LgpdController', 'action' => 'informationSecurity'],
    '/lgpd/account' => ['controller' => 'LgpdController', 'action' => 'account'],
    '/lgpd/advertising' => ['controller' => 'LgpdController', 'action' => 'advertising'],
    '/lgpd/disclaimer' => ['controller' => 'LgpdController', 'action' => 'disclaimer'],
    '/lgpd/integrations' => ['controller' => 'LgpdController', 'action' => 'integrations'],
    '/lgpd/responsible-use' => ['controller' => 'LgpdController', 'action' => 'responsibleUse'],
    '/lgpd/consent' => ['controller' => 'LgpdController', 'action' => 'consent'],
    '/lgpd/accept-consent' => ['controller' => 'LgpdController', 'action' => 'acceptConsent'],
    '/lgpd/revoke-consent' => ['controller' => 'LgpdController', 'action' => 'revokeConsent'],
    '/lgpd/export-data' => ['controller' => 'LgpdController', 'action' => 'exportData'],
    '/lgpd/delete-account' => ['controller' => 'LgpdController', 'action' => 'deleteAccountForm'],
    '/lgpd/delete-account/confirm' => ['controller' => 'LgpdController', 'action' => 'deleteAccount'],

    // Feed Social
    '/feed' => ['controller' => 'FeedController', 'action' => 'index'],
    '/feed/create' => ['controller' => 'FeedController', 'action' => 'create'],
    '/feed/store' => ['controller' => 'FeedController', 'action' => 'store'],
    '/feed/show/{id}' => ['controller' => 'FeedController', 'action' => 'show'],
    '/feed/delete/{id}' => ['controller' => 'FeedController', 'action' => 'delete'],
    '/feed/like/{id}' => ['controller' => 'FeedController', 'action' => 'like'],
    '/feed/comment/{id}' => ['controller' => 'FeedController', 'action' => 'comment'],
    '/feed/delete-comment/{id}' => ['controller' => 'FeedController', 'action' => 'deleteComment'],
    '/feed/share/{id}' => ['controller' => 'FeedController', 'action' => 'share'],
    '/feed/save/{id}' => ['controller' => 'FeedController', 'action' => 'save'],
    '/feed/saved' => ['controller' => 'FeedController', 'action' => 'saved'],
    '/feed/user/{id}' => ['controller' => 'FeedController', 'action' => 'userPosts'],
    '/feed/upload-image' => ['controller' => 'FeedController', 'action' => 'uploadImageAjax'],

    // Moderation (Denúncias e Moderação)
    '/moderation' => ['controller' => 'ModerationController', 'action' => 'index'],
    '/moderation/show/{id}' => ['controller' => 'ModerationController', 'action' => 'show'],
    '/moderation/create' => ['controller' => 'ModerationController', 'action' => 'create'],
    '/moderation/store' => ['controller' => 'ModerationController', 'action' => 'store'],
    '/moderation/update-status/{id}' => ['controller' => 'ModerationController', 'action' => 'updateStatus'],
    '/moderation/assign/{id}' => ['controller' => 'ModerationController', 'action' => 'assign'],
    '/moderation/my-reports' => ['controller' => 'ModerationController', 'action' => 'myReports'],
    '/moderation/block/{id}' => ['controller' => 'ModerationController', 'action' => 'blockUser'],
    '/moderation/unblock/{id}' => ['controller' => 'ModerationController', 'action' => 'unblockUser'],
    '/moderation/blocked' => ['controller' => 'ModerationController', 'action' => 'blockedList'],
    '/moderation/warnings' => ['controller' => 'ModerationController', 'action' => 'warnings'],
    '/moderation/warnings/{id}' => ['controller' => 'ModerationController', 'action' => 'warnings'],
    '/moderation/issue-warning/{id}' => ['controller' => 'ModerationController', 'action' => 'issueWarning'],
    '/moderation/revoke-warning/{id}' => ['controller' => 'ModerationController', 'action' => 'revokeWarning'],

    // Location (Geolocalização)
    '/location' => ['controller' => 'LocationController', 'action' => 'index'],
    '/location/update' => ['controller' => 'LocationController', 'action' => 'update'],
    '/location/toggle-sharing' => ['controller' => 'LocationController', 'action' => 'toggleSharing'],
    '/location/nearby' => ['controller' => 'LocationController', 'action' => 'nearby'],
    '/location/nearby-events' => ['controller' => 'LocationController', 'action' => 'nearbyEvents'],
    '/location/nearby-clubs' => ['controller' => 'LocationController', 'action' => 'nearbyClubs'],
    '/location/settings' => ['controller' => 'LocationController', 'action' => 'settings'],
    '/location/update-settings' => ['controller' => 'LocationController', 'action' => 'updateSettings'],

    // Gamification
    '/gamification' => ['controller' => 'GamificationController', 'action' => 'index'],
    '/gamification/show/{id}' => ['controller' => 'GamificationController', 'action' => 'show'],
    '/gamification/history' => ['controller' => 'GamificationController', 'action' => 'history'],
    '/gamification/achievements' => ['controller' => 'GamificationController', 'action' => 'achievements'],
    '/gamification/ranking' => ['controller' => 'GamificationController', 'action' => 'ranking'],
    '/gamification/levels' => ['controller' => 'GamificationController', 'action' => 'levels'],

    // Subscriptions (Pagamentos e Assinaturas)
    '/subscriptions/plans' => ['controller' => 'SubscriptionController', 'action' => 'plans'],
    '/subscriptions/subscribe/{id}' => ['controller' => 'SubscriptionController', 'action' => 'subscribe'],
    '/subscriptions/process/{id}' => ['controller' => 'SubscriptionController', 'action' => 'processPayment'],
    '/subscriptions/status/{id}' => ['controller' => 'SubscriptionController', 'action' => 'paymentStatus'],
    '/subscriptions/status-check/{id}' => ['controller' => 'SubscriptionController', 'action' => 'paymentStatus'],
    '/subscriptions/pix/{id}' => ['controller' => 'SubscriptionController', 'action' => 'pixQrCode'],
    '/subscriptions/webhook' => ['controller' => 'SubscriptionController', 'action' => 'webhook'],
    '/subscriptions/my' => ['controller' => 'SubscriptionController', 'action' => 'mySubscription'],
    '/subscriptions/cancel' => ['controller' => 'SubscriptionController', 'action' => 'cancel'],
    '/subscriptions/history' => ['controller' => 'SubscriptionController', 'action' => 'history'],
    '/subscriptions/success/{id}' => ['controller' => 'SubscriptionController', 'action' => 'success'],
    '/subscriptions/failure/{id}' => ['controller' => 'SubscriptionController', 'action' => 'failure'],

    // Advertisements (Publicidade)
    '/ads' => ['controller' => 'AdController', 'action' => 'index'],
    '/ads/create' => ['controller' => 'AdController', 'action' => 'create'],
    '/ads/store' => ['controller' => 'AdController', 'action' => 'store'],
    '/ads/edit/{id}' => ['controller' => 'AdController', 'action' => 'edit'],
    '/ads/update/{id}' => ['controller' => 'AdController', 'action' => 'update'],
    '/ads/delete/{id}' => ['controller' => 'AdController', 'action' => 'delete'],
    '/ads/stats/{id}' => ['controller' => 'AdController', 'action' => 'stats'],
    '/ads/pause/{id}' => ['controller' => 'AdController', 'action' => 'pause'],
    '/ads/resume/{id}' => ['controller' => 'AdController', 'action' => 'resume'],
    '/ads/admin' => ['controller' => 'AdController', 'action' => 'admin'],
    '/ads/approve/{id}' => ['controller' => 'AdController', 'action' => 'approve'],
    '/ads/reject/{id}' => ['controller' => 'AdController', 'action' => 'reject'],
    '/ads/track-impression/{id}' => ['controller' => 'AdController', 'action' => 'trackImpression'],
    '/ads/impression/{id}' => ['controller' => 'AdController', 'action' => 'trackImpression'],
    '/ads/track-click/{id}' => ['controller' => 'AdController', 'action' => 'trackClick'],
    '/ads/click/{id}' => ['controller' => 'AdController', 'action' => 'trackClick'],

    // Push Notifications
    '/push/register-device' => ['controller' => 'PushNotificationController', 'action' => 'registerDevice'],
    '/push/unregister-device' => ['controller' => 'PushNotificationController', 'action' => 'unregisterDevice'],
    '/push/preferences' => ['controller' => 'PushNotificationController', 'action' => 'preferences'],
    '/push/update-preferences' => ['controller' => 'PushNotificationController', 'action' => 'updatePreferences'],
    '/push/history' => ['controller' => 'PushNotificationController', 'action' => 'history'],
    '/push/test' => ['controller' => 'PushNotificationController', 'action' => 'test'],
    '/push/process-queue' => ['controller' => 'PushNotificationController', 'action' => 'processQueue'],

    // Advanced Gamification (MD-023)
    '/advanced-gamification' => ['controller' => 'AdvancedGamificationController', 'action' => 'index'],
    '/advanced-gamification/scores' => ['controller' => 'AdvancedGamificationController', 'action' => 'scores'],
    '/advanced-gamification/points-history' => ['controller' => 'AdvancedGamificationController', 'action' => 'pointsHistory'],
    '/advanced-gamification/challenges' => ['controller' => 'AdvancedGamificationController', 'action' => 'challenges'],
    '/advanced-gamification/challenges/{id}' => ['controller' => 'AdvancedGamificationController', 'action' => 'challengeDetail'],
    '/advanced-gamification/challenges/{id}/join' => ['controller' => 'AdvancedGamificationController', 'action' => 'joinChallenge'],
    '/advanced-gamification/rankings' => ['controller' => 'AdvancedGamificationController', 'action' => 'rankings'],
    '/advanced-gamification/seasons' => ['controller' => 'AdvancedGamificationController', 'action' => 'seasons'],
    '/advanced-gamification/medals' => ['controller' => 'AdvancedGamificationController', 'action' => 'medals'],
    '/advanced-gamification/invitations' => ['controller' => 'AdvancedGamificationController', 'action' => 'invitations'],
    '/advanced-gamification/invitations/create' => ['controller' => 'AdvancedGamificationController', 'action' => 'createInvitation'],
    '/advanced-gamification/invitations/validate' => ['controller' => 'AdvancedGamificationController', 'action' => 'validateInvitation'],

    // Trust System (MD-024)
    '/trust' => ['controller' => 'TrustController', 'action' => 'index'],
    '/trust/profile' => ['controller' => 'TrustController', 'action' => 'profile'],
    '/trust/profile/{id}' => ['controller' => 'TrustController', 'action' => 'profile'],
    '/trust/validate' => ['controller' => 'TrustController', 'action' => 'validate'],
    '/trust/validate/store' => ['controller' => 'TrustController', 'action' => 'validateStore'],
    '/trust/validations' => ['controller' => 'TrustController', 'action' => 'validations'],
    '/trust/residence' => ['controller' => 'TrustController', 'action' => 'residence'],
    '/trust/residence/store' => ['controller' => 'TrustController', 'action' => 'residenceStore'],
    '/trust/residence/checkin' => ['controller' => 'TrustController', 'action' => 'residenceCheckin'],
    '/trust/motorcycle-verify' => ['controller' => 'TrustController', 'action' => 'motorcycleVerify'],
    '/trust/blocks' => ['controller' => 'TrustController', 'action' => 'blocks'],
    '/trust/block' => ['controller' => 'TrustController', 'action' => 'block'],
    '/trust/unblock' => ['controller' => 'TrustController', 'action' => 'unblock'],
    '/trust/claims' => ['controller' => 'TrustController', 'action' => 'claims'],
    '/trust/claims/store' => ['controller' => 'TrustController', 'action' => 'claimClub'],
    '/trust/claims/review' => ['controller' => 'TrustController', 'action' => 'reviewClaim'],
    '/trust/audit-log' => ['controller' => 'TrustController', 'action' => 'auditLog'],

    // Tracking / HeatMap / Import (MD-025)
    '/tracking' => ['controller' => 'TrackingController', 'action' => 'index'],
    '/tracking/start' => ['controller' => 'TrackingController', 'action' => 'startTrip'],
    '/tracking/add-point' => ['controller' => 'TrackingController', 'action' => 'addPoint'],
    '/tracking/add-points' => ['controller' => 'TrackingController', 'action' => 'addPoints'],
    '/tracking/finish' => ['controller' => 'TrackingController', 'action' => 'finishTrip'],
    '/tracking/trip/{id}' => ['controller' => 'TrackingController', 'action' => 'tripDetail'],
    '/tracking/my-trips' => ['controller' => 'TrackingController', 'action' => 'myTrips'],
    '/tracking/import' => ['controller' => 'TrackingController', 'action' => 'import'],
    '/tracking/process-import' => ['controller' => 'TrackingController', 'action' => 'processImport'],
    '/tracking/import-status/{id}' => ['controller' => 'TrackingController', 'action' => 'importStatus'],
    '/tracking/delete-import/{id}' => ['controller' => 'TrackingController', 'action' => 'deleteImport'],
    '/tracking/delete/{id}' => ['controller' => 'TrackingController', 'action' => 'deleteTrip'],
    '/tracking/heatmap' => ['controller' => 'TrackingController', 'action' => 'heatmap'],
    '/tracking/community-heatmap' => ['controller' => 'TrackingController', 'action' => 'communityHeatmap'],
    '/tracking/passport' => ['controller' => 'TrackingController', 'action' => 'passport'],
    '/tracking/exploration-stats' => ['controller' => 'TrackingController', 'action' => 'explorationStats'],
    '/tracking/add-checkpoint' => ['controller' => 'TrackingController', 'action' => 'addCheckpoint'],

    // Event Participation
    '/events/participate/{id}' => ['controller' => 'EventController', 'action' => 'participate'],
    '/events/cancelParticipation/{id}' => ['controller' => 'EventController', 'action' => 'cancelParticipation'],
    '/events/participants/{id}' => ['controller' => 'EventController', 'action' => 'participants'],
    '/events/attendance/{id}' => ['controller' => 'EventController', 'action' => 'attendance'],
    '/events/invite/{id}' => ['controller' => 'EventController', 'action' => 'invite'],
    '/events/invitations/{id}' => ['controller' => 'EventController', 'action' => 'invitations'],
    '/events/respond-invitation/{id}' => ['controller' => 'EventController', 'action' => 'respondInvitation'],
    '/events/my-invitations' => ['controller' => 'EventController', 'action' => 'myInvitations'],

    // LGPD Data Export
    '/lgpd/export-data' => ['controller' => 'LgpdController', 'action' => 'exportData'],
    '/lgpd/request-export' => ['controller' => 'LgpdController', 'action' => 'requestExport'],
    '/lgpd/download-export/{id}' => ['controller' => 'LgpdController', 'action' => 'downloadExport'],
    '/lgpd/delete-export/{id}' => ['controller' => 'LgpdController', 'action' => 'deleteExport'],
    '/lgpd/delete-account' => ['controller' => 'LgpdController', 'action' => 'deleteAccount'],
    '/lgpd/request-deletion' => ['controller' => 'LgpdController', 'action' => 'requestDeletion'],
    '/lgpd/cancel-deletion' => ['controller' => 'LgpdController', 'action' => 'cancelDeletion'],

    // Bookmarks / Saved Items / Share
    '/bookmarks/toggle' => ['controller' => 'BookmarkController', 'action' => 'toggle'],
    '/bookmarks/saved' => ['controller' => 'BookmarkController', 'action' => 'saved'],
    '/bookmarks/share' => ['controller' => 'BookmarkController', 'action' => 'share'],

    // API Docs (Swagger)
    '/api-docs' => ['controller' => 'ApiDocsController', 'action' => 'index'],
    '/api-docs/spec' => ['controller' => 'ApiDocsController', 'action' => 'spec'],

    // Admin Jobs
    '/admin/jobs' => ['controller' => 'AdminController', 'action' => 'jobs'],
    '/admin/jobs/run' => ['controller' => 'AdminController', 'action' => 'runJobs'],
    '/admin/jobs/clear-failed' => ['controller' => 'AdminController', 'action' => 'clearFailedJobs'],

    // Admin — Club Claims (Reivindicações)
    '/admin/club-claims' => ['controller' => 'ClubController', 'action' => 'adminClaims'],
    '/admin/club-claims/{id}/approve' => ['controller' => 'ClubController', 'action' => 'approveClaim'],
    '/admin/club-claims/{id}/reject' => ['controller' => 'ClubController', 'action' => 'rejectClaim'],

    // Admin — Visitantes Únicos
    '/admin/visitors' => ['controller' => 'HomeController', 'action' => 'adminVisitors'],
    '/admin/app-logs' => ['controller' => 'HomeController', 'action' => 'adminAppLogs'],
    '/admin/app-logs/delete/{id}' => ['controller' => 'HomeController', 'action' => 'deleteAppLog'],

    // Admin — SEO
    '/admin/seo' => ['controller' => 'SEOAdminController', 'action' => 'index'],

    // Admin — Widgets
    '/admin/widgets' => ['controller' => 'WidgetController', 'action' => 'adminIndex'],
    '/admin/widgets/store' => ['controller' => 'WidgetController', 'action' => 'store'],
    '/admin/widgets/update/{id}' => ['controller' => 'WidgetController', 'action' => 'update'],
    '/admin/widgets/delete/{id}' => ['controller' => 'WidgetController', 'action' => 'delete'],
    '/admin/widgets/toggle/{id}' => ['controller' => 'WidgetController', 'action' => 'toggle'],
    '/admin/widgets/toggle-position' => ['controller' => 'WidgetController', 'action' => 'togglePosition'],

    // API REST v1
    '/api/auth/login' => ['controller' => 'Api\\AuthController', 'action' => 'login'],
    '/api/auth/register' => ['controller' => 'Api\\AuthController', 'action' => 'register'],
    '/api/auth/me' => ['controller' => 'Api\\AuthController', 'action' => 'me'],
    '/api/auth/refresh' => ['controller' => 'Api\\AuthController', 'action' => 'refresh'],
    '/api/auth/logout' => ['controller' => 'Api\\AuthController', 'action' => 'logout'],
    '/api/clubs' => ['controller' => 'Api\\ClubController', 'action' => 'index'],
    '/api/clubs/{id}' => ['controller' => 'Api\\ClubController', 'action' => 'show'],
    '/api/clubs/create' => ['controller' => 'Api\\ClubController', 'action' => 'store'],
    '/api/clubs/update/{id}' => ['controller' => 'Api\\ClubController', 'action' => 'update'],
    '/api/clubs/delete/{id}' => ['controller' => 'Api\\ClubController', 'action' => 'destroy'],
    '/api/clubs/{id}/members' => ['controller' => 'Api\\ClubController', 'action' => 'members'],
    '/api/clubs/{id}/join' => ['controller' => 'Api\\ClubController', 'action' => 'join'],
    '/api/clubs/{id}/leave' => ['controller' => 'Api\\ClubController', 'action' => 'leave'],
    '/api/posts' => ['controller' => 'Api\\PostController', 'action' => 'index'],
    '/api/posts/{id}' => ['controller' => 'Api\\PostController', 'action' => 'show'],
    '/api/posts/create' => ['controller' => 'Api\\PostController', 'action' => 'store'],
    '/api/posts/delete/{id}' => ['controller' => 'Api\\PostController', 'action' => 'destroy'],
    '/api/posts/{id}/like' => ['controller' => 'Api\\PostController', 'action' => 'like'],
    '/api/posts/{id}/comments' => ['controller' => 'Api\\PostController', 'action' => 'comment'],
    '/api/routes' => ['controller' => 'Api\\RouteController', 'action' => 'index'],
    '/api/routes/{id}' => ['controller' => 'Api\\RouteController', 'action' => 'show'],
    '/api/routes/create' => ['controller' => 'Api\\RouteController', 'action' => 'store'],
    '/api/routes/update/{id}' => ['controller' => 'Api\\RouteController', 'action' => 'update'],
    '/api/routes/delete/{id}' => ['controller' => 'Api\\RouteController', 'action' => 'destroy'],
    '/api/routes/map' => ['controller' => 'Api\\RouteController', 'action' => 'map'],
    '/api/travels' => ['controller' => 'Api\\TravelController', 'action' => 'index'],
    '/api/travels/{id}' => ['controller' => 'Api\\TravelController', 'action' => 'show'],
    '/api/travels/create' => ['controller' => 'Api\\TravelController', 'action' => 'store'],
    '/api/travels/update/{id}' => ['controller' => 'Api\\TravelController', 'action' => 'update'],
    '/api/travels/delete/{id}' => ['controller' => 'Api\\TravelController', 'action' => 'destroy'],
    '/api/messages' => ['controller' => 'Api\\MessageController', 'action' => 'index'],
    '/api/messages/{id}' => ['controller' => 'Api\\MessageController', 'action' => 'show'],
    '/api/messages/{id}/send' => ['controller' => 'Api\\MessageController', 'action' => 'send'],
    '/api/messages/conversations' => ['controller' => 'Api\\MessageController', 'action' => 'conversations'],
    '/api/subscriptions/plans' => ['controller' => 'Api\\SubscriptionController', 'action' => 'plans'],
    '/api/subscriptions/me' => ['controller' => 'Api\\SubscriptionController', 'action' => 'mySubscription'],
    '/api/subscriptions/subscribe' => ['controller' => 'Api\\SubscriptionController', 'action' => 'subscribe'],
    '/api/subscriptions/cancel' => ['controller' => 'Api\\SubscriptionController', 'action' => 'cancel'],

    // API — LGPD
    '/api/lgpd/export' => ['controller' => 'Api\\LgpdController', 'action' => 'export'],
    '/api/lgpd/exports' => ['controller' => 'Api\\LgpdController', 'action' => 'exports'],
    '/api/lgpd/exports/{id}/download' => ['controller' => 'Api\\LgpdController', 'action' => 'download'],

    // API — Bookmarks
    '/api/bookmarks/toggle' => ['controller' => 'Api\\BookmarkController', 'action' => 'toggle'],
    '/api/bookmarks' => ['controller' => 'Api\\BookmarkController', 'action' => 'list'],
    '/api/share' => ['controller' => 'Api\\BookmarkController', 'action' => 'share'],

    // API — Gamification
    '/api/gamification/scores' => ['controller' => 'Api\\GamificationController', 'action' => 'scores'],
    '/api/gamification/level' => ['controller' => 'Api\\GamificationController', 'action' => 'level'],
    '/api/gamification/challenges' => ['controller' => 'Api\\GamificationController', 'action' => 'challenges'],
    '/api/gamification/challenges/{id}/join' => ['controller' => 'Api\\GamificationController', 'action' => 'joinChallenge'],
    '/api/gamification/rankings' => ['controller' => 'Api\\GamificationController', 'action' => 'rankings'],
    '/api/gamification/seasons' => ['controller' => 'Api\\GamificationController', 'action' => 'seasons'],
    '/api/gamification/medals' => ['controller' => 'Api\\GamificationController', 'action' => 'medals'],
    '/api/gamification/achievements' => ['controller' => 'Api\\GamificationController', 'action' => 'achievements'],
    '/api/gamification/invite' => ['controller' => 'Api\\GamificationController', 'action' => 'invite'],
    '/api/gamification/invitations' => ['controller' => 'Api\\GamificationController', 'action' => 'invitations'],

    // API — Campaigns (Membro Pioneiro)
    '/api/campaigns/create' => ['controller' => 'Api\\CampaignController', 'action' => 'createCampaign'],
    '/api/campaigns/medals' => ['controller' => 'Api\\CampaignController', 'action' => 'listMedals'],
    '/api/campaigns/list' => ['controller' => 'Api\\CampaignController', 'action' => 'listCampaigns'],
    '/api/campaigns/stats/{campaignName}' => ['controller' => 'Api\\CampaignController', 'action' => 'campaignStats'],

    // Admin — Campaigns
    '/admin/campaigns' => ['controller' => 'AdminController', 'action' => 'campaigns'],
    '/admin/campaigns/create' => ['controller' => 'AdminController', 'action' => 'createCampaign'],
    '/admin/campaigns/stats/{campaignName}' => ['controller' => 'AdminController', 'action' => 'campaignStats'],
    '/admin/campaigns/export/{campaignName}' => ['controller' => 'AdminController', 'action' => 'exportCampaignLinks'],

    // API — Trust
    '/api/trust/score' => ['controller' => 'Api\\TrustController', 'action' => 'score'],
    '/api/trust/validations' => ['controller' => 'Api\\TrustController', 'action' => 'validations'],
    '/api/trust/validate' => ['controller' => 'Api\\TrustController', 'action' => 'validate'],
    '/api/trust/verifications/residence' => ['controller' => 'Api\\TrustController', 'action' => 'residenceVerifications'],
    '/api/trust/verifications/motorcycle' => ['controller' => 'Api\\TrustController', 'action' => 'motorcycleVerifications'],
    '/api/trust/blocks' => ['controller' => 'Api\\TrustController', 'action' => 'blocks'],
    '/api/trust/blocks/{id}' => ['controller' => 'Api\\TrustController', 'action' => 'unblock'],
    '/api/trust/audit' => ['controller' => 'Api\\TrustController', 'action' => 'audit'],

    // API — Tracking
    '/api/tracking/trips' => ['controller' => 'Api\\TrackingController', 'action' => 'trips'],
    '/api/tracking/trips/start' => ['controller' => 'Api\\TrackingController', 'action' => 'startTrip'],
    '/api/tracking/trips/{id}/point' => ['controller' => 'Api\\TrackingController', 'action' => 'addPoint'],
    '/api/tracking/trips/{id}/finish' => ['controller' => 'Api\\TrackingController', 'action' => 'finishTrip'],
    '/api/tracking/trips/{id}/pause' => ['controller' => 'Api\\TrackingController', 'action' => 'pauseTrip'],
    '/api/tracking/trips/{id}/resume' => ['controller' => 'Api\\TrackingController', 'action' => 'resumeTrip'],
    '/api/tracking/trips/{id}' => ['controller' => 'Api\\TrackingController', 'action' => 'tripDetails'],
    '/api/tracking/trips/{id}/checkpoint' => ['controller' => 'Api\\TrackingController', 'action' => 'addCheckpoint'],
    '/api/tracking/trips/{id}/delete' => ['controller' => 'Api\\TrackingController', 'action' => 'deleteTrip'],
    '/api/tracking/trips/{id}/update-gpx' => ['controller' => 'Api\\TrackingController', 'action' => 'updateFromGpx'],
    '/api/tracking/import' => ['controller' => 'Api\\TrackingController', 'action' => 'import'],
    '/api/tracking/imports' => ['controller' => 'Api\\TrackingController', 'action' => 'imports'],
    '/api/tracking/heatmap' => ['controller' => 'Api\\TrackingController', 'action' => 'heatmap'],
    '/api/tracking/heatmap/community' => ['controller' => 'Api\\TrackingController', 'action' => 'communityHeatmap'],
    '/api/tracking/passport' => ['controller' => 'Api\\TrackingController', 'action' => 'passport'],
    '/api/tracking/exploration-stats' => ['controller' => 'Api\\TrackingController', 'action' => 'explorationStats'],
    '/api/tracking/segments' => ['controller' => 'Api\\TrackingController', 'action' => 'segments'],

    // API — SOS (Mobile)
    '/api/sos/trigger' => ['controller' => 'Api\\SosController', 'action' => 'trigger'],
    '/api/sos/{id}/location' => ['controller' => 'Api\\SosController', 'action' => 'updateLocation'],
    '/api/sos/{id}/resolve' => ['controller' => 'Api\\SosController', 'action' => 'resolve'],
    '/api/sos/active' => ['controller' => 'Api\\SosController', 'action' => 'active'],
    '/api/sos/{id}' => ['controller' => 'Api\\SosController', 'action' => 'show'],

    // API — Logs do App (Mobile)
    '/api/logs' => ['controller' => 'Api\\LogController', 'action' => 'upload'],
    '/api/logs/download' => ['controller' => 'Api\\LogController', 'action' => 'download'],
    '/api/logs/latest' => ['controller' => 'Api\\LogController', 'action' => 'latest'],

    // Route Alerts
    '/route-alerts' => ['controller' => 'RouteAlertController', 'action' => 'index'],
    '/route-alerts/create' => ['controller' => 'RouteAlertController', 'action' => 'create'],
    '/route-alerts/store' => ['controller' => 'RouteAlertController', 'action' => 'store'],
    '/route-alerts/{id}/resolve' => ['controller' => 'RouteAlertController', 'action' => 'resolve'],
    '/route-alerts/{id}/delete' => ['controller' => 'RouteAlertController', 'action' => 'delete'],
    '/route-alerts/nearby' => ['controller' => 'RouteAlertController', 'action' => 'nearby'],

    // Compatibility
    '/compatibility/suggestions' => ['controller' => 'CompatibilityController', 'action' => 'suggestions'],
    '/compatibility/check/{id}' => ['controller' => 'CompatibilityController', 'action' => 'check'],

    // Motorcycle Documents
    '/motorcycles/{id}/documents/add' => ['controller' => 'MotorcycleController', 'action' => 'addDocument'],
    '/motorcycles/{id}/documents/delete' => ['controller' => 'MotorcycleController', 'action' => 'deleteDocument'],

    // Social Groups
    '/social-groups' => ['controller' => 'SocialGroupController', 'action' => 'index'],
    '/social-groups/create' => ['controller' => 'SocialGroupController', 'action' => 'create'],
    '/social-groups/store' => ['controller' => 'SocialGroupController', 'action' => 'store'],
    '/social-groups/show/{id}' => ['controller' => 'SocialGroupController', 'action' => 'show'],
    '/social-groups/join/{id}' => ['controller' => 'SocialGroupController', 'action' => 'join'],
    '/social-groups/leave/{id}' => ['controller' => 'SocialGroupController', 'action' => 'leave'],
    '/social-groups/{id}/rules/add' => ['controller' => 'SocialGroupController', 'action' => 'addRule'],
    '/social-groups/{id}/rules/delete' => ['controller' => 'SocialGroupController', 'action' => 'deleteRule'],
    '/social-groups/{id}/mural/add' => ['controller' => 'SocialGroupController', 'action' => 'addMuralPost'],
    '/social-groups/{id}/mural/delete' => ['controller' => 'SocialGroupController', 'action' => 'deleteMuralPost'],

    // Tribe Forum (Private)
    '/tribe-forum/topic/{id}' => ['controller' => 'TribeForumController', 'action' => 'topic'],
    '/tribe-forum/topic/create' => ['controller' => 'TribeForumController', 'action' => 'createTopic'],
    '/tribe-forum/topic/{id}/reply' => ['controller' => 'TribeForumController', 'action' => 'addReply'],
    '/tribe-forum/topic/{id}/pin' => ['controller' => 'TribeForumController', 'action' => 'togglePin'],
    '/tribe-forum/topic/{id}/lock' => ['controller' => 'TribeForumController', 'action' => 'toggleLock'],
    '/tribe-forum/topic/{id}/delete' => ['controller' => 'TribeForumController', 'action' => 'deleteTopic'],
    '/tribe-forum/topic/{id}/reply/{rid}/delete' => ['controller' => 'TribeForumController', 'action' => 'deleteReply'],

    // Convoys (Comboios)
    '/convoys' => ['controller' => 'ConvoyController', 'action' => 'index'],
    '/convoys/create' => ['controller' => 'ConvoyController', 'action' => 'create'],
    '/convoys/store' => ['controller' => 'ConvoyController', 'action' => 'store'],
    '/convoys/show/{id}' => ['controller' => 'ConvoyController', 'action' => 'show'],
    '/convoys/join/{id}' => ['controller' => 'ConvoyController', 'action' => 'join'],
    '/convoys/leave/{id}' => ['controller' => 'ConvoyController', 'action' => 'leave'],
    '/convoys/{id}/status' => ['controller' => 'ConvoyController', 'action' => 'updateStatus'],
    '/convoys/{id}/checkpoint/add' => ['controller' => 'ConvoyController', 'action' => 'addCheckpoint'],
    '/convoys/{id}/checkpoint/{cid}/status' => ['controller' => 'ConvoyController', 'action' => 'checkpointStatus'],
    '/convoys/{id}/delete' => ['controller' => 'ConvoyController', 'action' => 'delete'],

    // Maintenance Alerts
    '/maintenance-alerts' => ['controller' => 'MaintenanceAlertController', 'action' => 'index'],
    '/maintenance-alerts/mark-all-read' => ['controller' => 'MaintenanceAlertController', 'action' => 'markAllRead'],
    '/maintenance-alerts/{id}/read' => ['controller' => 'MaintenanceAlertController', 'action' => 'markRead'],
    '/maintenance-alerts/{id}/dismiss' => ['controller' => 'MaintenanceAlertController', 'action' => 'dismiss'],

    // Live Streams
    '/live-streams' => ['controller' => 'LiveStreamController', 'action' => 'index'],
    '/live-streams/create' => ['controller' => 'LiveStreamController', 'action' => 'create'],
    '/live-streams/store' => ['controller' => 'LiveStreamController', 'action' => 'store'],
    '/live-streams/show/{id}' => ['controller' => 'LiveStreamController', 'action' => 'show'],
    '/live-streams/{id}/start' => ['controller' => 'LiveStreamController', 'action' => 'start'],
    '/live-streams/{id}/end' => ['controller' => 'LiveStreamController', 'action' => 'end'],
    '/live-streams/{id}/cancel' => ['controller' => 'LiveStreamController', 'action' => 'cancel'],
    '/live-streams/{id}/delete' => ['controller' => 'LiveStreamController', 'action' => 'delete'],
    '/live-streams/{id}/like' => ['controller' => 'LiveStreamController', 'action' => 'like'],
    '/live-streams/{id}/chat/send' => ['controller' => 'LiveStreamController', 'action' => 'chatSend'],
    '/live-streams/{id}/chat/{mid}/delete' => ['controller' => 'LiveStreamController', 'action' => 'chatDelete'],
    '/live-streams/{id}/chat/{mid}/pin' => ['controller' => 'LiveStreamController', 'action' => 'chatPin'],

    // Commercial Ecosystem
    '/commercial/benefits' => ['controller' => 'CommercialController', 'action' => 'benefits'],
    '/commercial/benefits/{id}/use' => ['controller' => 'CommercialController', 'action' => 'useBenefit'],
    '/commercial/my-benefits' => ['controller' => 'CommercialController', 'action' => 'myBenefits'],
    '/commercial/promotions' => ['controller' => 'CommercialController', 'action' => 'promotions'],
    '/commercial/promotions/{id}' => ['controller' => 'CommercialController', 'action' => 'showPromotion'],
    '/commercial/promotions/{id}/use' => ['controller' => 'CommercialController', 'action' => 'usePromotion'],
    '/commercial/regional' => ['controller' => 'CommercialController', 'action' => 'regional'],

    // Social Auth (Login Social)
    '/social-auth/google/redirect' => ['controller' => 'SocialAuthController', 'action' => 'googleRedirect'],
    '/social-auth/google/callback' => ['controller' => 'SocialAuthController', 'action' => 'googleCallback'],
    '/social-auth/apple/redirect' => ['controller' => 'SocialAuthController', 'action' => 'appleRedirect'],
    '/social-auth/apple/callback' => ['controller' => 'SocialAuthController', 'action' => 'appleCallback'],
    '/social-auth/facebook/redirect' => ['controller' => 'SocialAuthController', 'action' => 'googleRedirect'],
    '/social-auth/phone/send' => ['controller' => 'SocialAuthController', 'action' => 'phoneSendCode'],
    '/social-auth/phone/verify' => ['controller' => 'SocialAuthController', 'action' => 'phoneVerifyForm'],
    '/social-auth/phone/verify/post' => ['controller' => 'SocialAuthController', 'action' => 'phoneVerify'],
    '/social-auth/linked-accounts' => ['controller' => 'SocialAuthController', 'action' => 'linkedAccounts'],
    '/social-auth/unlink/{provider}' => ['controller' => 'SocialAuthController', 'action' => 'unlink'],

    // 2FA (Two-Factor Authentication)
    '/2fa/setup' => ['controller' => 'TwoFactorController', 'action' => 'setup'],
    '/2fa/enable' => ['controller' => 'TwoFactorController', 'action' => 'enable'],
    '/2fa/enable/confirm' => ['controller' => 'TwoFactorController', 'action' => 'confirmEnable'],
    '/2fa/disable' => ['controller' => 'TwoFactorController', 'action' => 'disable'],
    '/2fa/regenerate-backup-codes' => ['controller' => 'TwoFactorController', 'action' => 'regenerateBackupCodes'],
    '/2fa/verify' => ['controller' => 'TwoFactorController', 'action' => 'verifyForm'],
    '/2fa/verify/post' => ['controller' => 'TwoFactorController', 'action' => 'verify'],
    '/2fa/sessions' => ['controller' => 'TwoFactorController', 'action' => 'sessions'],
    '/2fa/sessions/revoke' => ['controller' => 'TwoFactorController', 'action' => 'revokeSession'],
    '/2fa/sessions/revoke-all' => ['controller' => 'TwoFactorController', 'action' => 'revokeAllSessions'],

    // GraphQL API
    '/graphql' => ['controller' => 'Api\\GraphQLController', 'action' => 'index'],
    '/graphql/playground' => ['controller' => 'Api\\GraphQLController', 'action' => 'playground'],
    '/graphql/schema' => ['controller' => 'Api\\GraphQLController', 'action' => 'schema'],

    // AI — Inteligência Artificial
    '/ai/assistant' => ['controller' => 'AIController', 'action' => 'assistant'],
    '/ai/assistant/start' => ['controller' => 'AIController', 'action' => 'startConversation'],
    '/ai/assistant/send' => ['controller' => 'AIController', 'action' => 'sendMessage'],
    '/ai/recommendations' => ['controller' => 'AIController', 'action' => 'recommendations'],
    '/ai/recommendations/{id}/click' => ['controller' => 'AIController', 'action' => 'clickRecommendation'],
    '/ai/recommendations/{id}/dismiss' => ['controller' => 'AIController', 'action' => 'dismissRecommendation'],
    '/ai/predictions' => ['controller' => 'AIController', 'action' => 'predictions'],
    '/ai/predictions/{id}/dismiss' => ['controller' => 'AIController', 'action' => 'dismissPrediction'],
    '/ai/automations' => ['controller' => 'AIController', 'action' => 'automations'],
    '/ai/automations/create' => ['controller' => 'AIController', 'action' => 'createAutomation'],
    '/ai/automations/{id}/toggle' => ['controller' => 'AIController', 'action' => 'toggleAutomation'],
    '/ai/automations/{id}/delete' => ['controller' => 'AIController', 'action' => 'deleteAutomation'],

    // Mobile — PWA, Sync, Devices, Notifications
    '/mobile/sync' => ['controller' => 'MobileController', 'action' => 'sync'],
    '/mobile/sync/process' => ['controller' => 'MobileController', 'action' => 'processSync'],
    '/mobile/devices' => ['controller' => 'MobileController', 'action' => 'devices'],
    '/mobile/devices/unregister' => ['controller' => 'MobileController', 'action' => 'unregisterDevice'],
    '/mobile/notifications' => ['controller' => 'MobileController', 'action' => 'notifications'],
    '/manifest.json' => ['controller' => 'MobileController', 'action' => 'pwa'],
    '/sw.js' => ['controller' => 'MobileController', 'action' => 'serviceWorker'],
    '/offline' => ['controller' => 'MobileController', 'action' => 'offline'],

    '/api-docs' => ['controller' => 'ApiDocsController', 'action' => 'index'],

    // System Logs — Centralized Logging
    '/logs/system' => ['controller' => 'LogViewerController', 'action' => 'index'],
    '/logs/system/purge' => ['controller' => 'LogViewerController', 'action' => 'purge'],
    '/logs/system/file' => ['controller' => 'LogViewerController', 'action' => 'viewFile'],
    '/api/logs/frontend' => ['controller' => 'LogViewerController', 'action' => 'apiFrontendLog'],

    // Feed API for infinite scroll
    '/api/feed' => ['controller' => 'FeedController', 'action' => 'apiFeed'],
    '/api/logs' => ['controller' => 'LogController', 'action' => 'apiUpload'],

    // ============================================================
    // MOTOHEAD Encontros — Web Routes
    // ============================================================
    '/encontros' => ['controller' => 'DatingController', 'action' => 'index'],
    '/encontros/ativar' => ['controller' => 'DatingController', 'action' => 'activate'],
    '/encontros/ativar/post' => ['controller' => 'DatingController', 'action' => 'storeActivation'],
    '/encontros/descobrir' => ['controller' => 'DatingController', 'action' => 'discover'],
    '/encontros/matches' => ['controller' => 'DatingController', 'action' => 'matches'],
    '/encontros/perfil' => ['controller' => 'DatingController', 'action' => 'profile'],
    '/encontros/perfil/post' => ['controller' => 'DatingController', 'action' => 'updateProfile'],
    '/encontros/privacidade/post' => ['controller' => 'DatingController', 'action' => 'updatePrivacy'],
    '/encontros/pausar' => ['controller' => 'DatingController', 'action' => 'pause'],
    '/encontros/pausado' => ['controller' => 'DatingController', 'action' => 'paused'],
    '/encontros/reativar' => ['controller' => 'DatingController', 'action' => 'resume'],
    '/encontros/reativar/post' => ['controller' => 'DatingController', 'action' => 'resume'],
    '/encontros/desativar' => ['controller' => 'DatingController', 'action' => 'deactivate'],
    '/encontros/desativado' => ['controller' => 'DatingController', 'action' => 'deactivated'],
    '/encontros/perfil/{id}' => ['controller' => 'DatingController', 'action' => 'viewProfile'],
    '/encontros/bloqueios' => ['controller' => 'DatingController', 'action' => 'blocks'],
    '/encontros/foto/upload' => ['controller' => 'DatingController', 'action' => 'uploadPhoto'],
    '/encontros/foto/delete' => ['controller' => 'DatingController', 'action' => 'deletePhoto'],
    '/encontros/foto/principal' => ['controller' => 'DatingController', 'action' => 'setPrimaryPhoto'],
    '/encontros/foto/{id}' => ['controller' => 'DatingController', 'action' => 'servePhoto'],
    '/encontros/conversa/{id}' => ['controller' => 'DatingController', 'action' => 'conversation'],
    '/encontros/conversa/{id}/enviar' => ['controller' => 'DatingController', 'action' => 'sendMessage'],
    '/encontros/match/{id}' => ['controller' => 'DatingController', 'action' => 'matchCelebration'],
    '/encontros/seguranca' => ['controller' => 'DatingController', 'action' => 'safety'],

    // ============================================================
    // MOTOHEAD Encontros — API Routes
    // ============================================================
    '/api/dating/profile' => ['controller' => 'Api\DatingApiController', 'action' => 'getProfile'],
    '/api/dating/profile/update' => ['controller' => 'Api\DatingApiController', 'action' => 'updateProfile'],
    '/api/dating/activate' => ['controller' => 'Api\DatingApiController', 'action' => 'activate'],
    '/api/dating/pause' => ['controller' => 'Api\DatingApiController', 'action' => 'pause'],
    '/api/dating/deactivate' => ['controller' => 'Api\DatingApiController', 'action' => 'deactivate'],
    '/api/dating/discover' => ['controller' => 'Api\DatingApiController', 'action' => 'discover'],
    '/api/dating/like' => ['controller' => 'Api\DatingApiController', 'action' => 'like'],
    '/api/dating/dismiss' => ['controller' => 'Api\DatingApiController', 'action' => 'dismiss'],
    '/api/dating/matches' => ['controller' => 'Api\DatingApiController', 'action' => 'matches'],
    '/api/dating/profile/{id}' => ['controller' => 'Api\DatingApiController', 'action' => 'viewProfile'],
    '/api/dating/block' => ['controller' => 'Api\DatingApiController', 'action' => 'block'],
    '/api/dating/unblock' => ['controller' => 'Api\DatingApiController', 'action' => 'unblock'],
    '/api/dating/report' => ['controller' => 'Api\DatingApiController', 'action' => 'report'],
    '/api/dating/match/end' => ['controller' => 'Api\DatingApiController', 'action' => 'endMatch'],
    '/api/dating/privacy' => ['controller' => 'Api\DatingApiController', 'action' => 'updatePrivacy'],
    '/api/dating/dashboard' => ['controller' => 'Api\DatingApiController', 'action' => 'dashboard'],
    '/api/dating/photo/upload' => ['controller' => 'Api\DatingApiController', 'action' => 'uploadPhoto'],
    '/api/dating/photo/delete' => ['controller' => 'Api\DatingApiController', 'action' => 'deletePhoto'],
    '/api/dating/photo/primary' => ['controller' => 'Api\DatingApiController', 'action' => 'setPrimaryPhoto'],
    '/api/dating/photo/{id}' => ['controller' => 'Api\DatingApiController', 'action' => 'servePhoto'],
    '/api/dating/conversa/{id}' => ['controller' => 'Api\DatingApiController', 'action' => 'conversation'],
    '/api/dating/conversa/{id}/enviar' => ['controller' => 'Api\DatingApiController', 'action' => 'sendMessage'],

    // ============================================================
    // MOTOHEAD Encontros — Admin Routes
    // ============================================================
    '/admin/encontros' => ['controller' => 'DatingAdminController', 'action' => 'index'],
    '/admin/encontros/denuncias' => ['controller' => 'DatingAdminController', 'action' => 'reports'],
    '/admin/encontros/denuncia/resolver' => ['controller' => 'DatingAdminController', 'action' => 'resolveReport'],
    '/admin/encontros/suspender' => ['controller' => 'DatingAdminController', 'action' => 'suspendProfile'],
    '/admin/encontros/limitar' => ['controller' => 'DatingAdminController', 'action' => 'limitProfile'],
    '/admin/encontros/reativar-admin' => ['controller' => 'DatingAdminController', 'action' => 'reinstateProfile'],

    // ============================================================
    // MVCE — Virtual Community Engine Admin
    // ============================================================
    '/admin/virtual' => ['controller' => 'VirtualAdminController', 'action' => 'index'],
    '/admin/virtual/batch' => ['controller' => 'VirtualAdminController', 'action' => 'runBatch'],
    '/admin/virtual/queue' => ['controller' => 'VirtualAdminController', 'action' => 'processQueue'],
    '/admin/virtual/toggle' => ['controller' => 'VirtualAdminController', 'action' => 'toggle'],
    '/admin/virtual/reset' => ['controller' => 'VirtualAdminController', 'action' => 'resetCounts'],
    '/admin/virtual/seed' => ['controller' => 'VirtualAdminController', 'action' => 'seed'],
];

return $routes;
